/// Color scheme enumeration
/// Must match the WGSL shader switch statement indices exactly
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum ColorScheme {
    Classic = 0,
    Fire = 1,
    Ocean = 2,
    Rainbow = 3,
    Grayscale = 4,
    Electric = 5,
    Neon = 6,
    Sunset = 7,
    Forest = 8,
    Lava = 9,
    Ice = 10,
    Plasma = 11,
    Cosmic = 12,
    Autumn = 13,
    Matrix = 14,
    Vintage = 15,
    Candy = 16,
    Metal = 17,
    Toxic = 18,
    Aurora = 19,
    Desert = 20,
    DeepSea = 21,
    Magma = 22,
    BWBands = 23,
    Psychedelic = 24,
    Thermal = 25,
}

impl ColorScheme {
    pub fn all() -> &'static [ColorScheme] {
        &[
            ColorScheme::Classic,
            ColorScheme::Fire,
            ColorScheme::Ocean,
            ColorScheme::Rainbow,
            ColorScheme::Grayscale,
            ColorScheme::Electric,
            ColorScheme::Neon,
            ColorScheme::Sunset,
            ColorScheme::Forest,
            ColorScheme::Lava,
            ColorScheme::Ice,
            ColorScheme::Plasma,
            ColorScheme::Cosmic,
            ColorScheme::Autumn,
            ColorScheme::Matrix,
            ColorScheme::Vintage,
            ColorScheme::Candy,
            ColorScheme::Metal,
            ColorScheme::Toxic,
            ColorScheme::Aurora,
            ColorScheme::Desert,
            ColorScheme::DeepSea,
            ColorScheme::Magma,
            ColorScheme::BWBands,
            ColorScheme::Psychedelic,
            ColorScheme::Thermal,
        ]
    }

    pub fn name(&self) -> &'static str {
        match self {
            ColorScheme::Classic => "Classic",
            ColorScheme::Fire => "Fire",
            ColorScheme::Ocean => "Ocean",
            ColorScheme::Rainbow => "Rainbow",
            ColorScheme::Grayscale => "Grayscale",
            ColorScheme::Electric => "Electric",
            ColorScheme::Neon => "Neon",
            ColorScheme::Sunset => "Sunset",
            ColorScheme::Forest => "Forest",
            ColorScheme::Lava => "Lava",
            ColorScheme::Ice => "Ice",
            ColorScheme::Plasma => "Plasma",
            ColorScheme::Cosmic => "Cosmic",
            ColorScheme::Autumn => "Autumn",
            ColorScheme::Matrix => "Matrix",
            ColorScheme::Vintage => "Vintage",
            ColorScheme::Candy => "Candy",
            ColorScheme::Metal => "Metal",
            ColorScheme::Toxic => "Toxic",
            ColorScheme::Aurora => "Aurora",
            ColorScheme::Desert => "Desert",
            ColorScheme::DeepSea => "Deep Sea",
            ColorScheme::Magma => "Magma",
            ColorScheme::BWBands => "B&W Bands",
            ColorScheme::Psychedelic => "Psychedelic",
            ColorScheme::Thermal => "Thermal",
        }
    }

    pub fn from_u32(value: u32) -> Self {
        match value {
            0 => ColorScheme::Classic,
            1 => ColorScheme::Fire,
            2 => ColorScheme::Ocean,
            3 => ColorScheme::Rainbow,
            4 => ColorScheme::Grayscale,
            5 => ColorScheme::Electric,
            6 => ColorScheme::Neon,
            7 => ColorScheme::Sunset,
            8 => ColorScheme::Forest,
            9 => ColorScheme::Lava,
            10 => ColorScheme::Ice,
            11 => ColorScheme::Plasma,
            12 => ColorScheme::Cosmic,
            13 => ColorScheme::Autumn,
            14 => ColorScheme::Matrix,
            15 => ColorScheme::Vintage,
            16 => ColorScheme::Candy,
            17 => ColorScheme::Metal,
            18 => ColorScheme::Toxic,
            19 => ColorScheme::Aurora,
            20 => ColorScheme::Desert,
            21 => ColorScheme::DeepSea,
            22 => ColorScheme::Magma,
            23 => ColorScheme::BWBands,
            24 => ColorScheme::Psychedelic,
            25 => ColorScheme::Thermal,
            _ => ColorScheme::Classic,
        }
    }
}
